name: tech-vault-web

on:
  push:
    branches: main
#   schedule:
#     - cron: '21 3 * * 0' # weekly build

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: write

    steps:
    - name: Check out
      uses: actions/checkout@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and Publish (tech-vault-web)
      run: |
        registry="moabukar"
        tag="tools:tech-vault-web"
        docker build . -f Dockerfile -t ${registry}/${tag}
        docker push ${registry}/${tag}
